import Script from "next/script"
import Link from "next/link"
import { Receipt, Download, Printer, Share2, CheckCircle } from "lucide-react"
import { SiteLogo } from "@/components/shared/site-logo"

export const metadata = {
  title: "Free Rent Receipt Generator | Download PDF | Turnivo",
  description:
    "Generate professional rent receipts online for free. Download as PDF. Perfect for tenants claiming HRA and landlords issuing receipts. No signup needed.",
  alternates: {
    canonical: "https://Turnivo.in/rent-receipt-generator",
  },
}

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      "name": "What is a rent receipt?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "A rent receipt is a document issued by a landlord to a tenant as proof of rent payment. It includes the tenant name, landlord name, property address, rent amount, payment date, and payment mode.",
      },
    },
    {
      "@type": "Question",
      "name": "Is a rent receipt mandatory for HRA tax exemption?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes, if you are claiming House Rent Allowance (HRA) exemption under Section 10(13A) of the Income Tax Act, you need rent receipts as proof of payment. For rent above ₹3,000 per month, the receipt must have a revenue stamp.",
      },
    },
    {
      "@type": "Question",
      "name": "Can I use this rent receipt for IT returns?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes, the rent receipt generated by Turnivo includes all fields required by the Income Tax Department — landlord name, tenant name, property address, rent amount, and payment details.",
      },
    },
    {
      "@type": "Question",
      "name": "Is this rent receipt generator really free?",
      "acceptedAnswer": {
        "@type": "Answer",
        "text": "Yes, completely free. No watermarks, no signup, no hidden charges. Generate unlimited rent receipts and download as PDF instantly.",
      },
    },
  ],
}

const features = [
  { icon: Receipt, title: "GST & HRA Compliant", desc: "Includes all fields required for HRA claims and GST purposes." },
  { icon: Download, title: "Instant PDF Download", desc: "Download your rent receipt as a professional PDF with one click." },
  { icon: Printer, title: "Friendly Print Layout", desc: "Optimized for printing with clean formatting and proper margins." },
  { icon: Share2, title: "Share via WhatsApp", desc: "Share the receipt directly with your tenant or landlord." },
]

const steps = [
  { num: "01", title: "Fill in Details", desc: "Enter landlord name, tenant name, property address, rent amount, and payment month." },
  { num: "02", title: "Preview Receipt", desc: "Review the auto-generated receipt with proper formatting and all required fields." },
  { num: "03", title: "Download PDF", desc: "Download your rent receipt as a PDF and share it instantly with your landlord or tenant." },
]

export default function RentReceiptGeneratorPage() {
  return (
    <>
      <Script id="json-ld-1" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <div className="min-h-screen bg-mesh">
        <section className="py-16 sm:py-24 px-4">
          <div className="max-w-4xl mx-auto text-center">
            <SiteLogo className="mb-8" />
            <div className="h-14 w-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-6">
              <Receipt className="h-7 w-7 text-primary" />
            </div>
            <p className="text-sm font-semibold text-primary tracking-widest uppercase mb-3">Free Online Tool</p>
            <h1 className="text-4xl sm:text-5xl font-display font-bold tracking-tight mb-4">
              Free Rent Receipt Generator
            </h1>
            <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Create professional rent receipts in seconds. Perfect for tenants claiming HRA exemption and landlords
              issuing payment proof. Download as PDF — no signup needed.
            </p>
            <div className="flex flex-wrap justify-center gap-3 mt-8">
              <Link
                href="/rent-receipt"
                className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-xl font-medium hover:bg-primary/90 transition-colors shadow-lg shadow-primary/20"
              >
                <Receipt className="h-4 w-4" /> Generate Rent Receipt
              </Link>
            </div>
          </div>
        </section>

        <section className="py-12 sm:py-16 px-4 bg-white/50 dark:bg-gray-950/50">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl sm:text-3xl font-display font-bold text-center mb-10">Features</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {features.map((f) => (
                <div key={f.title} className="glass-card p-5 text-center space-y-3">
                  <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center mx-auto">
                    <f.icon className="h-5 w-5 text-primary" />
                  </div>
                  <h3 className="font-display font-semibold text-sm">{f.title}</h3>
                  <p className="text-xs text-muted-foreground">{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="py-12 sm:py-16 px-4">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl sm:text-3xl font-display font-bold text-center mb-10">How It Works</h2>
            <div className="grid sm:grid-cols-3 gap-6">
              {steps.map((s) => (
                <div key={s.num} className="text-center">
                  <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
                    <span className="text-lg font-bold text-primary">{s.num}</span>
                  </div>
                  <h3 className="font-display font-semibold mb-1">{s.title}</h3>
                  <p className="text-sm text-muted-foreground">{s.desc}</p>
                </div>
              ))}
            </div>
            <div className="text-center mt-8">
              <Link
                href="/rent-receipt"
                className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-6 py-3 rounded-xl font-medium hover:bg-primary/90 transition-colors"
              >
                Get Started Now <CheckCircle className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </section>

        <section className="py-12 sm:py-16 px-4 bg-white/50 dark:bg-gray-950/50">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl sm:text-3xl font-display font-bold text-center mb-10">
              Frequently Asked Questions
            </h2>
            <div className="space-y-3">
              {[
                { q: "What is a rent receipt?", a: "A rent receipt is a document issued by a landlord to a tenant as proof of rent payment. It includes the tenant name, landlord name, property address, rent amount, payment date, and payment mode." },
                { q: "Is a rent receipt mandatory for HRA tax exemption?", a: "Yes, if you are claiming House Rent Allowance (HRA) exemption under Section 10(13A) of the Income Tax Act, you need rent receipts as proof of payment. For rent above ₹3,000 per month, the receipt must have a revenue stamp." },
                { q: "Can I use this rent receipt for IT returns?", a: "Yes, the rent receipt generated by Turnivo includes all fields required by the Income Tax Department — landlord name, tenant name, property address, rent amount, and payment details." },
                { q: "Is this rent receipt generator really free?", a: "Yes, completely free. No watermarks, no signup, no hidden charges. Generate unlimited rent receipts and download as PDF instantly." },
              ].map((faq, i) => (
                <details key={i} className="glass-card p-5 group open:shadow-sm">
                  <summary className="font-display font-semibold text-sm cursor-pointer list-none flex items-center justify-between gap-4">
                    {faq.q}
                    <span className="text-muted-foreground shrink-0 transition-transform group-open:rotate-180">▼</span>
                  </summary>
                  <p className="mt-3 text-sm text-muted-foreground leading-relaxed">{faq.a}</p>
                </details>
              ))}
            </div>
          </div>
        </section>
      </div>
    </>
  )
}
